apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: ssm-store
spec:
  provider:
    aws:
      service: SSM
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: externalsecrets
