apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nat20
  labels:
    app: frontend
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Pod-level security + writable volumes for NGINX on read-only rootfs
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101

      # Make /etc/nginx/conf.d, /var/cache/nginx and /var/run writable via emptyDir
      initContainers:
        - name: init-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              set -eu
              mkdir -p /etc/nginx/conf.d /var/cache/nginx /var/run
              chown -R 101:101 /etc/nginx/conf.d /var/cache/nginx /var/run
          volumeMounts:
            - name: confd
              mountPath: /etc/nginx/conf.d
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run

      containers:
        - name: frontend
          image: ${IMAGE_URI}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: api_host
              value: "api.nat20scheduling.com"
          readinessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: confd
              mountPath: /etc/nginx/conf.d
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run

      restartPolicy: Always

      volumes:
        - name: confd
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: nat20
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
