name: Deploy Backend to EKS

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/deploy_backend.yml"
      - "infrastructure/docker/backend/Dockerfile"
      - "infrastructure/k8s/backend/**"
      - "infrastructure/k8s/externalsecrets/**"
      - "infrastructure/k8s/mongo/**"
      - "infrastructure/k8s/ingress/backend-ingress.yaml"
      - "infrastructure/k8s/secret-stores/clustersecretstore.yaml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-central-1
      CLUSTER_NAME: nat20-eks

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: whoami
        shell: bash
        run: |
          set -euo pipefail
          aws sts get-caller-identity
          aws configure list

      - name: Resolve ECR URI and SSM parameters (robust)
        id: resolve
        shell: bash
        run: |
          set -euo pipefail
          ECR_BACKEND_URI="$(aws ssm get-parameter --name /nat20/ecr/BACKEND_URI --query Parameter.Value --output text 2>/dev/null || true)"
          if [ -z "${ECR_BACKEND_URI:-}" ] || [ "${ECR_BACKEND_URI}" = "None" ]; then
            ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
            REPO_NAME="backend"
            ECR_BACKEND_URI="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}"
            aws ecr describe-repositories --repository-names "${REPO_NAME}" >/dev/null 2>&1 || \
              aws ecr create-repository --repository-name "${REPO_NAME}" >/dev/null
          fi
          echo "ECR_BACKEND_URI=${ECR_BACKEND_URI}" >> "$GITHUB_ENV"

          API_CERT_ARN="$(aws ssm get-parameter --name /nat20/network/API_CERT_ARN --query Parameter.Value --output text 2>/dev/null || true)"
          ALB_BACKEND_SG_ID="$(aws ssm get-parameter --name /nat20/network/ALB_BACKEND_SG_ID --query Parameter.Value --output text 2>/dev/null || true)"
          if [ -z "${API_CERT_ARN:-}" ] || [ "${API_CERT_ARN}" = "None" ]; then
            echo "Missing SSM parameter: /nat20/network/API_CERT_ARN" >&2; exit 1
          fi
          if [ -z "${ALB_BACKEND_SG_ID:-}" ] || [ "${ALB_BACKEND_SG_ID}" = "None" ]; then
            echo "Missing SSM parameter: /nat20/network/ALB_BACKEND_SG_ID" >&2; exit 1
          fi
          echo "API_CERT_ARN=${API_CERT_ARN}" >> "$GITHUB_ENV"
          echo "ALB_BACKEND_SG_ID=${ALB_BACKEND_SG_ID}" >> "$GITHUB_ENV"
          echo "API_HOST=api.nat20scheduling.com" >> "$GITHUB_ENV"

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        shell: bash
        run: |
          set -euo pipefail
          docker build -t "${ECR_BACKEND_URI}:${GITHUB_SHA}" -f infrastructure/docker/backend/Dockerfile .
          docker push "${ECR_BACKEND_URI}:${GITHUB_SHA}"
          echo "BACKEND_IMAGE=${ECR_BACKEND_URI}:${GITHUB_SHA}" >> "$GITHUB_ENV"

      - name: Update image in k8s manifest
        shell: bash
        run: |
          set -euo pipefail
          sed -i "s#<ECR_URI_REPLACED_BY_CI>/backend:\${GITHUB_SHA}#${ECR_BACKEND_URI}:${GITHUB_SHA}#g" infrastructure/k8s/backend/deployment.yaml

      - name: Capture current EKS API CIDRs
        shell: bash
        run: |
          set -euo pipefail
          ORIG="$(aws eks describe-cluster --name "${CLUSTER_NAME}" --region "${AWS_REGION}" \
            --query 'cluster.resourcesVpcConfig.publicAccessCidrs' --output text | sed 's/\t/,/g')"
          echo "ORIGINAL_EKS_API_CIDRS=${ORIG}" >> "$GITHUB_ENV"

      - name: Temporarily restrict EKS API to runner egress IP
        shell: bash
        run: |
          set -euo pipefail
          RUNNER_IP="$(curl -s https://checkip.amazonaws.com)/32"
          aws eks update-cluster-config --name "${CLUSTER_NAME}" --region "${AWS_REGION}" \
            --resources-vpc-config publicAccessCidrs="${RUNNER_IP}"

      - name: Configure kubectl
        shell: bash
        run: |
          set -euo pipefail
          aws eks update-kubeconfig --name "${CLUSTER_NAME}" --region "${AWS_REGION}"

      - name: Ensure namespaces exist + enforce PSS (restricted)
        shell: bash
        run: |
          set -euo pipefail
          kubectl get ns nat20 >/dev/null 2>&1 || kubectl create ns nat20
          kubectl get ns externalsecrets >/dev/null 2>&1 || kubectl create ns externalsecrets
          kubectl label ns nat20 \
            pod-security.kubernetes.io/enforce=restricted \
            pod-security.kubernetes.io/audit=restricted \
            pod-security.kubernetes.io/warn=restricted \
            --overwrite

      - name: Ensure External Secrets CRDs (server-side, pinned)
        shell: bash
        run: |
          set -euo pipefail
          kubectl apply --server-side -f https://raw.githubusercontent.com/external-secrets/external-secrets/v0.19.2/deploy/crds/bundle.yaml
          kubectl wait --for=condition=Established crd clustersecretstores.external-secrets.io --timeout=180s
          kubectl wait --for=condition=Established crd secretstores.external-secrets.io --timeout=180s
          kubectl wait --for=condition=Established crd externalsecrets.external-secrets.io --timeout=180s

      - name: Resolve ALB subnets for this cluster
        shell: bash
        run: |
          set -euo pipefail
          SUBNETS_CSV="$(aws eks describe-cluster --name "${CLUSTER_NAME}" --region "${AWS_REGION}" --query 'cluster.resourcesVpcConfig.subnetIds' --output text | sed 's/\t/,/g')"
          [ -z "${SUBNETS_CSV:-}" ] && { echo "Could not resolve cluster subnets" >&2; exit 1; }
          echo "ALB_PUBLIC_SUBNET_IDS=${SUBNETS_CSV}" >> "$GITHUB_ENV"

      - name: Preflight check SSM params for ExternalSecret
        shell: bash
        run: |
          set -euo pipefail
          MISSING=0
          for KEY in /nat20/backend/JWT_SECRET /nat20/mongo/USER /nat20/mongo/PASSWORD /nat20/mongo/DB; do
            if ! aws ssm get-parameter --name "$KEY" >/dev/null 2>&1; then
              echo "Missing SSM parameter: $KEY" >&2; MISSING=1
            fi
          done
          [ $MISSING -ne 0 ] && { echo "Required SSM parameters missing; aborting." >&2; exit 1; }

      - name: Apply ClusterSecretStore and ExternalSecret
        shell: bash
        run: |
          set -euo pipefail
          kubectl apply -f infrastructure/k8s/secret-stores/clustersecretstore.yaml
          kubectl -n nat20 delete externalsecret backend-secrets --ignore-not-found=true
          kubectl apply -n nat20 -f infrastructure/k8s/externalsecrets/backend-secrets.yaml
          kubectl -n nat20 wait --for=condition=Ready externalsecret.external-secrets.io/backend-secrets --timeout=300s
          for i in $(seq 1 60); do
            kubectl -n nat20 get secret backend-env >/dev/null 2>&1 && break
            echo "Waiting for backend-env Secret... ($i/60)"; sleep 5
          done

      - name: Render backend ingress (envsubst)
        shell: bash
        run: |
          set -euo pipefail
          : "${ALB_PUBLIC_SUBNET_IDS:?ALB_PUBLIC_SUBNET_IDS is not set}"
          : "${API_CERT_ARN:?API_CERT_ARN is not set}"
          : "${ALB_BACKEND_SG_ID:?ALB_BACKEND_SG_ID is not set}"
          : "${API_HOST:?API_HOST is not set}"
          API_CERT_ARN="${API_CERT_ARN}" \
          ALB_BACKEND_SG_ID="${ALB_BACKEND_SG_ID}" \
          API_HOST="${API_HOST}" \
          ALB_PUBLIC_SUBNET_IDS="${ALB_PUBLIC_SUBNET_IDS}" \
          envsubst < infrastructure/k8s/ingress/backend-ingress.yaml > /tmp/backend-ingress.rendered.yaml

      - name: Apply backend Service/Deployment and Ingress
        shell: bash
        run: |
          set -euo pipefail
          kubectl apply -n nat20 -f infrastructure/k8s/backend/deployment.yaml
          kubectl apply -f /tmp/backend-ingress.rendered.yaml
          kubectl rollout status deployment/backend -n nat20 --timeout=300s

      - name: Wait for Backend Ingress hostname (ALB provisioning)
        id: alb
        shell: bash
        run: |
          set -euo pipefail
          for i in $(seq 1 90); do
            HOSTNAME="$(kubectl -n nat20 get ingress backend -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || true)"
            if [ -n "${HOSTNAME:-}" ] && [ "${HOSTNAME}" != "<no value>" ]; then break; fi
            echo "Waiting for Ingress ALB hostname... ($i/90)"; sleep 10
          done
          [ -z "${HOSTNAME:-}" ] || [ "${HOSTNAME}" = "<no value>" ] && { kubectl -n nat20 describe ingress backend || true; exit 1; }
          echo "BACKEND_ALB_DNS=${HOSTNAME}" >> "$GITHUB_ENV"
          echo "backend_alb_dns=${HOSTNAME}" >> "$GITHUB_OUTPUT"

      - name: Restore EKS API CIDRs to original
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${ORIGINAL_EKS_API_CIDRS:-}" ]; then
            aws eks update-cluster-config --name "${CLUSTER_NAME}" --region "${AWS_REGION}" \
              --resources-vpc-config publicAccessCidrs="${ORIGINAL_EKS_API_CIDRS}"
          else
            echo "No ORIGINAL_EKS_API_CIDRS captured; leaving current setting in place."
          fi
