name: Deploy Stack (Terraform ➜ Mongo ➜ Backend ➜ Frontend)

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  group: nat20-eks-ops
  cancel-in-progress: true

env:
  AWS_REGION: eu-central-1

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform -chdir=infrastructure/terraform init -input=false

      - name: Terraform Apply
        env:
          TF_IN_AUTOMATION: "true"
        run: terraform -chdir=infrastructure/terraform apply -input=false -lock-timeout=2m -auto-approve

  mongo:
    name: Deploy Mongo
    needs: terraform
    uses: navotj/Scheduler-v3/.github/workflows/deploy_mongo.yml@main
    secrets: inherit

  backend:
    name: Deploy Backend
    needs: mongo
    uses: navotj/Scheduler-v3/.github/workflows/deploy_backend.yml@main
    secrets: inherit

  frontend:
    name: Deploy Frontend
    needs: backend
    uses: navotj/Scheduler-v3/.github/workflows/deploy_frontend.yml@main
    secrets: inherit
