name: Deploy Backend to EC2

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/app/**'
      - 'backend/service'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BACKEND_USER: ec2-user

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Fetch backend public IP from AWS
        run: |
          BACKEND_IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=terraform-backend" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].PublicIpAddress" \
            --output text)
          echo "BACKEND_IP=$BACKEND_IP" >> $GITHUB_ENV
          echo "Resolved backend IP: $BACKEND_IP"

      - name: Write SSH private key to file
        run: |
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' | awk '{gsub(/\\n/,"\n")}1' > private_key.pem
          chmod 600 private_key.pem

      - name: Create target directory on remote
        run: |
            ssh -o StrictHostKeyChecking=no -i private_key.pem $BACKEND_USER@${{ env.BACKEND_IP }} \
            "sudo mkdir -p /opt/app && sudo chown -R $BACKEND_USER /opt/app"

      - name: Copy backend app to EC2
        run: |
          echo "Deploying to $BACKEND_USER@${{ env.BACKEND_IP }}"
          scp -o StrictHostKeyChecking=no -i private_key.pem -r backend/app/. $BACKEND_USER@${{ env.BACKEND_IP }}:/opt/app

      - name: Copy systemd service file to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem backend/service $BACKEND_USER@${{ env.BACKEND_IP }}:/tmp/myapp.service

      - name: Install systemd service and restart app
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $BACKEND_USER@${{ env.BACKEND_IP }} << 'EOF'
            sudo mv /tmp/myapp.service /etc/systemd/system/myapp.service
            sudo systemctl daemon-reexec
            sudo systemctl daemon-reload
            sudo systemctl enable --now myapp
          EOF

      - name: Cleanup private key
        if: always()
        run: rm -f private_key.pem
