name: 'Deploy Terraform Infrastructure'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infrastructure/terraform/**'
      - ".github/workflows/deploy_terraform.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Deploy Terraform Infrastructure'
    runs-on: ubuntu-latest

    env:
      TF_VAR_admin_mongo_user: ${{ secrets.TF_VAR_ADMIN_MONGO_USER }}
      TF_VAR_admin_mongo_password: ${{ secrets.TF_VAR_ADMIN_MONGO_PASSWORD }}
      TF_VAR_s3_mongo_user: ${{ secrets.TF_VAR_s3_MONGO_USER }}
      TF_VAR_s3_mongo_password: ${{ secrets.TF_VAR_s3_MONGO_PASSWORD }}

    environment: Development

    defaults:
      run:
        shell: bash
        working-directory: infrastructure/terraform

    steps:
    # Checkout repo
    - name: Checkout
      uses: actions/checkout@v4

    # Setup Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # AWS credentials for both Terraform and AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    # Init Terraform
    - name: Terraform Init
      run: terraform init

    # Format Terraform files
    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Format Check
      run: terraform fmt -check

    # Terraform Plan (always runs)
    - name: Terraform Plan
      run: terraform plan -input=false

    # Apply only on push to main
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    - name: Export Terraform Outputs
      id: export_outputs
      working-directory: infrastructure/terraform
      run: |
        set -euo pipefail

        declare -A outputs=(
          ["BACKEND_IP"]="backend_instance_ip"
          ["MONGODB_IP"]="mongodb_instance_ip"
          ["BACKEND_PRIVATE_IP"]="backend_instance_private_ip"
          ["MONGODB_PRIVATE_IP"]="mongodb_instance_private_ip"
          ["BACKEND_INSTANCE_ID"]="backend_instance_id"
          ["MONGODB_INSTANCE_ID"]="mongodb_instance_id"
          ["MONGODB_EBS_VOLUME_ID"]="mongodb_ebs_volume_id"
        )

        for key in "${!outputs[@]}"; do
          value=$(terraform output -raw "${outputs[$key]}" 2>/dev/null || echo "")
          # Sanitize line breaks and colons that break GitHub env format
          clean_value=$(echo "$value" | tr -d '\r\n')
          echo "$key=$clean_value" >> "$GITHUB_ENV"
        done
