name: Terraform Apply (EKS hardened)

on:
  workflow_dispatch:

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-central-1
      TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.tf-plugin-cache
      TF_VAR_admin_principal_arn: ${{ secrets.EKS_ADMIN_PRINCIPAL_ARN }}

    defaults:
      run:
        shell: bash
        working-directory: infrastructure/terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gh-terraform-apply

      - name: Prepare Terraform plugin cache
        run: |
          mkdir -p "$TF_PLUGIN_CACHE_DIR"
          echo "plugin_cache_dir = \"$TF_PLUGIN_CACHE_DIR\"" > ~/.terraformrc
          ls -la "$TF_PLUGIN_CACHE_DIR"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -lock-timeout=2m -out=tfplan

      - name: Terraform Apply (full)
        run: terraform apply -input=false -lock-timeout=2m -auto-approve tfplan

      - name: Output
        run: terraform output -json || true
