name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      TF_VAR_mongodb_user: ${{ secrets.TF_VAR_MONGODB_USER }}
      TF_VAR_mongodb_password: ${{ secrets.TF_VAR_MONGODB_PASSWORD }}

    environment: Development

    defaults:
      run:
        shell: bash

    steps:
    # Checkout repo
    - name: Checkout
      uses: actions/checkout@v4

    # Setup Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # AWS credentials for both Terraform and AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    # Init Terraform
    - name: Terraform Init
      run: terraform init

    # Format Terraform files
    - name: Terraform Format
      run: terraform fmt

    - name: Terraform Format Check
      run: terraform fmt -check

    # Terraform Plan (always runs)
    - name: Terraform Plan
      run: terraform plan -input=false

    # Apply only on push to main
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false

    # Extract MongoDB EC2 instance ID to env (after apply)
    - name: Get MongoDB Instance ID
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: get_instance_id
      run: |
        INSTANCE_ID=$(terraform output -raw mongodb_instance_id)
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

    # Use AWS SSM to restart mongod via instance ID
    - name: Restart MongoDB via SSM
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Restart mongod" \
          --instance-ids "$INSTANCE_ID" \
          --parameters commands=["sudo systemctl restart mongod"] \
          --region eu-central-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        INSTANCE_ID: ${{ env.INSTANCE_ID }}
