name: Recreate MongoDB Instance

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'RECREATE' to confirm"
        required: true

jobs:
  recreate-mongodb:
    if: github.event.inputs.confirm == 'RECREATE'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Taint MongoDB Instance
        run: terraform taint aws_instance.mongodb
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply (Recreate MongoDB only)
        run: |
          terraform apply \
            -target=aws_instance.mongodb \
            -target=aws_volume_attachment.mongo_data_attachment \
            -auto-approve \
            -var="mongodb_user=dummy" \
            -var="mongodb_password=dummy"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
