name: Destroy MongoDB Instance

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'DESTROY' to confirm"
        required: true

jobs:
  destroy-mongodb:
    if: github.event.inputs.confirm == 'DESTROY'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Destroy MongoDB
        run: |
            terraform destroy \
            -target=aws_instance.mongodb \
            -auto-approve \
            -input=false \
            -var="mongodb_user=dummy" \
            -var="mongodb_password=dummy"
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
